### PR TITLE
Enable Enarxbot v2

### PR DESCRIPTION
**Pull request by mbestavros**
Signed-off-by: Mark Bestavros <mbestavr@redhat.com>

### CODE REVIEW

**Comment by lkatalin** [comment]
@mbestavros clippy has problems here too.

**Review by connorkuehl — APPROVED** [review]
Lint failures are unrelated and are fixed in #11

**Comment by connorkuehl** [comment]
@mbestavros was closing this PR intentional?

**Comment by mbestavros** [comment]
@connorkuehl https://github.com/enarx/enarx-keepmgr/pull/13

**Comment by mbestavros** [comment]
@connorkuehl Just realized what this was for. Yes, this was an unintentional closing. Will reopen.

**Comment by mbestavros** [comment]
@connorkuehl For real this time: https://github.com/enarx/enarx-keepmgr/pull/14

**Pull request closed without merging**
